FacturaWeb/Models/Customer.cs
namespace FacturaWeb.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }
        public string FullName { get; set; }
        public string DNI { get; set; }
    }
}

FacturaWeb/Models/FilteredOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FacturaWeb.Models
{
    public class FilteredOrder
    {
        public int OrderID { get; set; }
        public Customer Customer { get; set; }
        public DateTime OrderDate { get; set; }
        public bool Active { get; set; }
        public List<OrderDetail> OrderDetail { get; set; }
    }
}

FacturaWeb/Models/Order.cs
using System;
using System.Collections.Generic;

namespace FacturaWeb.Models
{
    public class Order
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public DateTime OrderDate { get; set; }
        public bool Active { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

FacturaWeb/Models/OrderDetail.cs
namespace FacturaWeb.Models
{
    public class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int Quantity { get; set; }
        public int ProductID { get; set; }
        public float Price { get; set; }
        public virtual Product Product { get; set; }
    }
}

FacturaWeb/Models/Product.cs
namespace FacturaWeb.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public double Price { get; set; }
    }
}

FacturaWeb/Models/SpecificOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FacturaWeb.Models
{
    public class SpecificOrder
    {

        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }


    }
}

FacturaWeb/Controllers/CustomerController.cs
using FacturaWeb.Proxy;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FacturaWeb.Controllers
{
    public class CustomerController : Controller
    {
        readonly CustomerProxy proxy = new CustomerProxy();

        [HttpGet]
        //public async Task<JsonResult> GetProducts()
        public JsonResult GetCustomers()
        {
            var response = Task.Run(() => proxy.GetCustomersAsync());
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }
    }
}

FacturaWeb/Controllers/FacturaController.cs
using FacturaWeb.Models;
using FacturaWeb.Requests;
using MVCAjax.Proxy;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FacturaWeb.Controllers
{
    public class FacturaController : Controller
    {

        readonly OrderProxy proxy = new OrderProxy();

        // GET: List Factura
        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetOrders()
        {
            var response = Task.Run(() => proxy.GetOrderAsync());
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }

        // GET: List Factura By ID
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateOrder(CreateOrderRequest request)
        {
            var order = JsonConvert.DeserializeObject<Order>(request.ToString());
            var response = Task.Run(() => proxy.InsertAsync(order));
            return Json(response.Result.Mensaje, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public JsonResult DeleteOrder(int id)
        {
            var response = Task.Run(() => proxy.DeleteOrderAsync(id));
            return Json(response.Result.Mensaje, JsonRequestBehavior.AllowGet);
        }
    }
}

FacturaWeb/Controllers/HomeController.cs
using System.Web.Mvc;

namespace FacturaWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

FacturaWeb/Controllers/OrderController.cs
using FacturaWeb.Models;
using FacturaWeb.Requests;
using MVCAjax.Proxy;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FacturaWeb.Controllers
{
    public class OrderController : Controller
    {

        readonly OrderProxy proxy = new OrderProxy();

        // GET: List Factura
        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetOrders()
        {
            var response = Task.Run(() => proxy.GetOrderAsync());
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }

        // GET: List Factura By ID
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateOrder(CreateOrderRequest request)
        {
            var order = JsonConvert.DeserializeObject<Order>(request.ToString());
            var response = Task.Run(() => proxy.InsertAsync(order));
            return Json(response.Result.Mensaje, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public JsonResult DeleteOrder(int id)
        {
            var response = Task.Run(() => proxy.DeleteOrderAsync(id));
            return Json(response.Result.Mensaje, JsonRequestBehavior.AllowGet);
        }
    }
}

FacturaWeb/Controllers/OrderDetailController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using FacturaWeb.Models;
using FacturaWeb.Proxy;
using FacturaWeb.Requests;
using Newtonsoft.Json;

namespace FacturaWeb.Controllers
{
    public class OrderDetailController: Controller
    {
        readonly OrderDetailProxy proxy = new OrderDetailProxy();

        [HttpGet]
        //public async Task<JsonResult> GetOrderDetails()
        public JsonResult GetOrderDetails(int id)
        {
            var response = Task.Run(() => proxy.GetOrderDetailsById(id));
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CreateOrderDetail(CreateOrderDetailRequest request)
        {
            var orderDetail = JsonConvert.DeserializeObject<OrderDetail>(request.ToString());
            var response = Task.Run(() => proxy.InsertAsync(orderDetail));
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }
    }
}

FacturaWeb/Controllers/ProductController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using FacturaWeb.Proxy;
using Newtonsoft.Json;

namespace FacturaWeb.Controllers
{
    public class ProductController : Controller
    {
        readonly ProductProxy proxy = new ProductProxy();

        [HttpGet]
        //public async Task<JsonResult> GetProducts()
        public JsonResult GetProducts()
        {
            var response = Task.Run(() => proxy.GetProductsAsync());
            return Json(response.Result.Listado, JsonRequestBehavior.AllowGet);
        }
    }
}

FacturaWeb/Views/Factura/List.cshtml
@model IEnumerable<FacturaWeb.Models.Order>

@{
    ViewBag.Title = "Listar Factura";
}


<!-- Begin Page Content -->
<div class="container-fluid">

    <br>

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Facturas</h1>

    <br>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Nueva Orden</h6>
        </div>
        <div class="card-body">
            <form>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="clientId">Cliente</label>
                                </div>
                                <select class="custom-select" id="clientId" name="clientId">
                                    <option selected>Seleccionar...</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="orderDdate">Fecha</label>
                                </div>
                                <input type="date" class="form-control" id="orderDdate" name="orderDdate" />
                            </div>
                        </div>
                        <div class="col-sm my-2">
                            <div class="input-group justify-content-center">
                                <a id="btnSave" class="btn btn-block mx-5 btn-primary">Crear Orden</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <br>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Filtros</h6>
        </div>
        <div class="card-body">
            <form>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="clientId">Cliente</label>
                                </div>
                                <select class="custom-select" id="clientId" name="clientId">
                                    <option selected>Seleccionar...</option>
                                    <option value="1">Cliente 1</option>
                                    <option value="2">Cliente 2</option>
                                    <option value="3">Cliente 3</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="productId">Producto</label>
                                </div>
                                <select class="custom-select" id="productId" name="productId">
                                    <option selected>Seleccionar...</option>
                                    <option value="1">Prodcuto 1</option>
                                    <option value="2">Prodcuto 2</option>
                                    <option value="3">Prodcuto 3</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="facturaId"># Factura</label>
                                </div>
                                <input type="text" class="form-control" placeholder="Codigo de Factura" id="facturaId"
                                       name="facturaId" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="dateFrom">Fecha desde</label>
                                </div>
                                <input type="date" class="form-control" id="dateFrom" name="dateFrom" />
                            </div>
                        </div>
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="dateTo">Fecha hasta</label>
                                </div>
                                <input type="date" class="form-control" id="dateTo" name="dateTo" />
                            </div>
                        </div>
                        <div class="col-sm my-2">
                            <div class="input-group justify-content-center">
                                <a id="btnSearch" class="btn btn-block mx-5 btn-primary">Buscar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista de Facturas</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th># Factura</th>
                            <th>Fecha</th>
                            <th>Cliente</th>
                            <th>Total</th>
                            <th>Acci&oacute;n</th>
                            <th>Ver</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th># Factura</th>
                            <th>Fecha</th>
                            <th>Cliente</th>
                            <th>Total</th>
                            <th>Acci&oacute;n</th>
                            <th>Ver</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        console.log('https://localhost:44393' + '@Url.Action("GetOrders")');
        $(function () {
            LoadData();
            LoadAllClients();

            function LoadData() {
                $("#dataTable tbody tr").remove();

                $.ajax({
                    url: 'https://localhost:44393' + '@Url.Action("GetOrders")',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log(data);
                        $.each(data, function (i, item) {
                            var rows = "<tr id='row" + item.OrderID + "'>"
                                + "<td>" + item.OrderID + "</td>"
                                + "<td>" + item.OrderDate + "</td>"
                                + "<td>" + item.CustomerID + "</td>"
                                //+ "<td>" + item.Customer.FullName + "</td>"
                                + "<td>" + 1200 + "</td>"
                                //+ "<td>" + item.orderDetails + "</td>"
                                + `${
                                    item.Active
                                    ? "<td><a type='button' class='btn btn-danger' onclick='cancelOrder(" + item.OrderID + ")'>Cancelar</a></td>"
                                    : "<td><a type='button' class='btn btn-success' onclick='enableOrder(" + item.OrderID + ")'>Activar</a></td>"
                                }`
                                + "<td><a type='button' class='btn btn-info' href=/Factura/Details/" + item.OrderID +">Detalles</a></td>"
                                //+ "<td><a type='button' class='btn btn-info' onclick='getDetails(" + item.OrderID + ")'>Detalles</a></td>"
                                + "</tr>";
                            $("#dataTable tbody").append(rows);
                        })
                    },
                    error: function (response) {
                        console.log(response)
                        var r = jQuery.parseJSON(response.responseText);
                        alert('Message: ' + r.Message);
                        alert('StackTrace: ' + r.StackTrace);
                        alert('ExceptionType: ' + r.ExceptionType);
                    }
                });

                return false;
            }

            $("#btnSave").click(function () {
                var order = {};
                order.CustomerID= Number($("#clientId option:selected").val());
                order.OrderDate = $("#orderDdate").val();
                //order.Active = true;
                CreateOrder(order);
            })

            function CreateOrder(order) {
                $.ajax({
                    type: "POST",
                    url: 'https://localhost:44393' + '@Url.Action("CreateOrder")',
                    data: '{ request: ' + JSON.stringify(order) + ' }',
                    //data: JSON.stringify(order),
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log(data);
                    },
                    error: function (response) {
                        console.log('ERROR')
                        console.log(response)
                    }
                });
            }

            function LoadAllClients() {
                $.ajax({
                    url: 'https://localhost:44393' + '@Url.Action("GetCustomers")',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log('LoadAllClients');
                        console.log(data);
                        $.each(data, function (i, item) {
                            var option = `<option value=${item.CustomerID}>${item.FullName} (${item.DNI})</option>`;
                            $("#clientId").append(option);
                        })
                    },
                    error: function (response) {
                        console.log('ERROR')
                        console.log(response)
                    }
                });

                return false;
            }
        });
    </script>
}

FacturaWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Factura - Trabajo Final";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12">
            <h2>INTEGRANTES:</h2>
            <ul>
                <li>Hervias Salas, Jadir Omar</li>
                <li>Mogoll&oacute;n Buitr&oacute;n, Khail Andr&eacute;s</li>
                <li>Salas Lej&oacute;a Geynaro Francisa</li>
                <li>Vizcarra Pedraza, Marco Aurelio</li>
            </ul>
        </div>
    </div>
</div>

FacturaWeb/Views/Order/Details.cshtml
@{
    ViewBag.Title = "Detalle de Factura";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <br>

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Agregar Producto</h1>

    <br>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Agregar</h6>
        </div>
        <div class="card-body">
            <form>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="productId">Producto</label>
                                </div>
                                <select class="custom-select" id="productsSelect" name="productId">
                                    <option selected>Seleccionar...</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md my-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="cantidad">Cantidad</label>
                                </div>
                                <input type="number" class="form-control" id="cantidad" name="cantidad" placeholder="0" aria-label="Ingrese la cantidad de Productos" aria-describedby="addon-wrapping" />
                            </div>
                        </div>

                        <div class="col-sm my-2">
                            <div class="input-group justify-content-center">
                                <a id="btnSave" class="btn btn-block mx-5 btn-primary">Agregar</a>
                            </div>
                        </div>

                    </div>

                </div>
            </form>
        </div>
    </div>

    <br>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Productos Agregados a la Factura</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Cliente</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio</th>
                            <th>Subtotal</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Cliente</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio</th>
                            <th>Subtotal</th>
                            <th>Eliminar</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@section Scripts
{
    <script type="text/javascript">

        const orderId = @Url.RequestContext.RouteData.Values["id"];
        console.log(orderId)
        const url = 'https://localhost:44393' + '@Url.Action("CreateOrderDetail")';
        console.log(url);
        $(function () {
            LoadData();
            LoadAllProducts()

            function LoadData() {
                $("#dataTable tbody tr").remove();
                $.ajax({
                    url: 'https://localhost:44393' + '@Url.Action("GetOrderDetailsById")' + '/' + orderId,
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log(data);
                        $.each(data, function (i, item) {
                            var rows = "<tr id='row" + item.OrderID + '-' + item.OrderDetailID + "'>"
                                + "<td>" + 'CLIENTE CTMR!!!!' + "</td>"
                                + "<td>" + item.Product?.ProductName + "</td>"
                                + "<td>" + item.Quantity + "</td>"
                                + "<td>" + item.Product?.Price + "</td>"
                                + "<td>" + Math.round(item.Product?.Price ? (item.Product.Price * item.Quantity) : 0) + "</td>"
                                + "<td><a type='button' class='btn btn-danger' onclick='deleteDetail(" + item.OrderDetailID + ")'>Eliminar</a></td>"
                                + "</tr>";
                            $("#dataTable tbody").append(rows);
                        })
                    },
                    error: function (response) {
                        console.log('ERROR')
                        console.log(response)
                    }
                });

                return false;
            }

            function LoadAllProducts() {
                $.ajax({
                    url: 'https://localhost:44393' + '@Url.Action("GetProducts")',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log('LoadAllProducts');
                        console.log(data);
                        $.each(data, function (i, item) {
                            var option = `<option value=${item.ProductID}>${item.ProductName}</option>`;
                            $("#productsSelect").append(option);
                        })
                    },
                    error: function (response) {
                        console.log('ERROR')
                        console.log(response)
                    }
                });

                return false;
            }

            $("#btnSave").click(function () {
                var orderDetail = {};
                orderDetail.OrderID = orderId;
                orderDetail.ProductID = Number($("#productsSelect option:selected").val());
                orderDetail.Quantity = Number($("#cantidad").val());
                CreateOrderDetails(orderDetail);
            })

            function CreateOrderDetails(orderDetail) {
                console.log(orderDetail)
                $.ajax({
                    type: "POST",
                    url,
                    data: '{ request: ' + JSON.stringify(orderDetail) + ' }',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        console.log(data);
                    },
                    error: function (response) {
                        console.log('ERROR')
                        console.log(response)
                    }
                });

                return false;
            }
        });
    </script>
}

FacturaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aluka</title>
    <!-- Custom fonts for this template -->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <li class="sidebar-brand d-flex align-items-center justify-content-center"
                style="padding: 12px">

                <div class="sidebar-brand-icon">
                    <i class="fas fa-laugh-wink"> </i>
                </div>

                <div class="sidebar-brand-text mx-3">
                    Aluka Admin
                </div>

            </li>

            <!-- Divider -->
            <hr class="sidebar-divider my-1" />

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">

                <span class="nav-link collapsed"
                      data-toggle="collapse"
                      data-target="#collapseTwo"
                      aria-expanded=true
                      aria-controls="collapseTwo">

                    <i class="fas fa-fw fa-cog"></i>
                    <span>Facturas</span>

                </span>
                <div id="collapseTwo"
                     class="collapse"
                     aria-labelledby="headingTwo"
                     data-parent="#accordionSidebar">

                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Operaciones</h6>
                        @Html.ActionLink("Listar facturas", "List", "Factura", null, new { @class = "collapse-item" })
                    </div>

                </div>
            </li>

            <hr className="sidebar-divider d-none d-md-block" />

            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Start Content wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">



                @RenderBody()

                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Tecsup 2021</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <!-- Content Wrapper -->

    </div>



    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)

</body>

</html>